# Copyright (c) 2026, Omnexa and contributors
# License: MIT. See license.txt
"""Bilingual (EN/AR) chart-of-accounts seed templates for production readiness.

`name_en` / `name_ar` are combined at generation time based on the requesting user's language.
Optional: pl_bucket, cash_flow_section, working_capital_bucket (GL Account fields).
"""

from __future__ import annotations

# --- Core structure (numeric codes stable for integrations / demo journal entries) ---

BASE_COA_TEMPLATE: list[dict] = [
	# Root & groups
	{
		"code": "1",
		"name_en": "Assets",
		"name_ar": "الأصول",
		"type": "Asset",
		"group": 1,
		"main": "Assets",
		"sub": "Header",
	},
	{
		"code": "11",
		"name_en": "Current Assets",
		"name_ar": "الأصول المتداولة",
		"type": "Asset",
		"group": 1,
		"parent": "1",
		"main": "Assets",
		"sub": "Current Assets",
	},
	{
		"code": "1101",
		"name_en": "Petty Cash",
		"name_ar": "النقدية بالصندوق",
		"type": "Asset",
		"group": 0,
		"parent": "11",
		"main": "Assets",
		"sub": "Cash",
		"cash_flow_section": "Operating Activities",
		"working_capital_bucket": "Exclude",
	},
	{
		"code": "1102",
		"name_en": "Bank Accounts – Operating",
		"name_ar": "حسابات بنكية – تشغيل",
		"type": "Asset",
		"group": 0,
		"parent": "11",
		"main": "Assets",
		"sub": "Bank",
		"cash_flow_section": "Operating Activities",
		"working_capital_bucket": "Exclude",
	},
	{
		"code": "1103",
		"name_en": "Trade Receivables",
		"name_ar": "عملاء / ذمم مدينة تجارية",
		"type": "Asset",
		"group": 0,
		"parent": "11",
		"main": "Assets",
		"sub": "Receivables",
		"cash_flow_section": "Operating Activities",
		"working_capital_bucket": "Trade Receivables",
	},
	{
		"code": "1104",
		"name_en": "Inventory",
		"name_ar": "المخزون",
		"type": "Asset",
		"group": 0,
		"parent": "11",
		"main": "Assets",
		"sub": "Inventory",
		"is_stock_valuation": 1,
		"cash_flow_section": "Operating Activities",
		"working_capital_bucket": "Inventory",
	},
	{
		"code": "1105",
		"name_en": "Advances to Suppliers",
		"name_ar": "دفعات مقدمة للموردين",
		"type": "Asset",
		"group": 0,
		"parent": "11",
		"main": "Assets",
		"sub": "Prepayments",
		"cash_flow_section": "Operating Activities",
		"working_capital_bucket": "Other Working Capital",
	},
	{
		"code": "1106",
		"name_en": "Input VAT Recoverable",
		"name_ar": "ضريبة القيمة المضافة مدخلات (قابلة للاسترداد)",
		"type": "Asset",
		"group": 0,
		"parent": "11",
		"main": "Assets",
		"sub": "Tax",
		"cash_flow_section": "Operating Activities",
		"working_capital_bucket": "Other Working Capital",
	},
	{
		"code": "1107",
		"name_en": "Other Receivables",
		"name_ar": "ذمم مدينة أخرى",
		"type": "Asset",
		"group": 0,
		"parent": "11",
		"main": "Assets",
		"sub": "Receivables",
		"cash_flow_section": "Operating Activities",
		"working_capital_bucket": "Other Working Capital",
	},
	{
		"code": "1110",
		"name_en": "Projects - Contract Assets (Unbilled Revenue)",
		"name_ar": "المشاريع - أصول عقود (إيراد غير مفوتر)",
		"type": "Asset",
		"group": 0,
		"parent": "11",
		"main": "Assets",
		"sub": "Trade Receivables",
		"cash_flow_section": "Operating Activities",
		"working_capital_bucket": "Trade Receivables",
	},
	{
		"code": "1111",
		"name_en": "Projects - Retention Receivable",
		"name_ar": "المشاريع - ضمانات مستردة لدى العملاء",
		"type": "Asset",
		"group": 0,
		"parent": "11",
		"main": "Assets",
		"sub": "Trade Receivables",
		"cash_flow_section": "Operating Activities",
		"working_capital_bucket": "Trade Receivables",
	},
	{
		"code": "1112",
		"name_en": "Projects - Work in Progress (WIP)",
		"name_ar": "المشاريع - أعمال تحت التنفيذ",
		"type": "Asset",
		"group": 0,
		"parent": "11",
		"main": "Assets",
		"sub": "Inventory",
		"cash_flow_section": "Operating Activities",
		"working_capital_bucket": "Inventory",
	},
	{
		"code": "1113",
		"name_en": "Projects - Advance Payments to Subcontractors",
		"name_ar": "المشاريع - دفعات مقدمة لمقاولين من الباطن",
		"type": "Asset",
		"group": 0,
		"parent": "11",
		"main": "Assets",
		"sub": "Prepayments",
		"cash_flow_section": "Operating Activities",
		"working_capital_bucket": "Other Working Capital",
	},
	{
		"code": "1114",
		"name_en": "Projects - Mobilization & Deferred Project Costs",
		"name_ar": "المشاريع - تكاليف تعبئة وتكاليف مؤجلة",
		"type": "Asset",
		"group": 0,
		"parent": "11",
		"main": "Assets",
		"sub": "Prepayments",
		"cash_flow_section": "Operating Activities",
		"working_capital_bucket": "Other Working Capital",
	},
	{
		"code": "12",
		"name_en": "Non-Current Assets",
		"name_ar": "الأصول غير المتداولة",
		"type": "Asset",
		"group": 1,
		"parent": "1",
		"main": "Assets",
		"sub": "Non-Current Assets",
	},
	{
		"code": "1201",
		"name_en": "Property, Plant & Equipment",
		"name_ar": "الممتلكات والمعدات والأصول الثابتة",
		"type": "Asset",
		"group": 0,
		"parent": "12",
		"main": "Assets",
		"sub": "PPE",
		"cash_flow_section": "Investing Activities",
		"working_capital_bucket": "Exclude",
	},
	{
		"code": "1202",
		"name_en": "Intangible Assets",
		"name_ar": "الأصول غير الملموسة",
		"type": "Asset",
		"group": 0,
		"parent": "12",
		"main": "Assets",
		"sub": "Intangibles",
		"cash_flow_section": "Investing Activities",
		"working_capital_bucket": "Exclude",
	},
	{
		"code": "1203",
		"name_en": "Long-Term Investments",
		"name_ar": "استثمارات طويلة الأجل",
		"type": "Asset",
		"group": 0,
		"parent": "12",
		"main": "Assets",
		"sub": "Investments",
		"cash_flow_section": "Investing Activities",
		"working_capital_bucket": "Exclude",
	},
	{
		"code": "1204",
		"name_en": "Right-of-Use Assets (IFRS 16)",
		"name_ar": "أصول حق الاستخدام (IFRS 16)",
		"type": "Asset",
		"group": 0,
		"parent": "12",
		"main": "Assets",
		"sub": "ROU Assets",
		"cash_flow_section": "Investing Activities",
		"working_capital_bucket": "Exclude",
	},
	# Liabilities
	{
		"code": "2",
		"name_en": "Liabilities",
		"name_ar": "الخصوم",
		"type": "Liability",
		"group": 1,
		"main": "Liabilities",
		"sub": "Header",
	},
	{
		"code": "21",
		"name_en": "Current Liabilities",
		"name_ar": "الخصوم المتداولة",
		"type": "Liability",
		"group": 1,
		"parent": "2",
		"main": "Liabilities",
		"sub": "Current Liabilities",
	},
	{
		"code": "2101",
		"name_en": "Trade Payables",
		"name_ar": "موردون / ذمم دائنة تجارية",
		"type": "Liability",
		"group": 0,
		"parent": "21",
		"main": "Liabilities",
		"sub": "Payables",
		"cash_flow_section": "Operating Activities",
		"working_capital_bucket": "Trade Payables",
	},
	{
		"code": "2102",
		"name_en": "Accrued Expenses",
		"name_ar": "مصروفات مستحقة",
		"type": "Liability",
		"group": 0,
		"parent": "21",
		"main": "Liabilities",
		"sub": "Accruals",
		"cash_flow_section": "Operating Activities",
		"working_capital_bucket": "Other Working Capital",
	},
	{
		"code": "2103",
		"name_en": "Output VAT Payable",
		"name_ar": "ضريبة القيمة المضافة مخرجات (مستحقة)",
		"type": "Liability",
		"group": 0,
		"parent": "21",
		"main": "Liabilities",
		"sub": "Tax",
		"cash_flow_section": "Operating Activities",
		"working_capital_bucket": "Other Working Capital",
	},
	{
		"code": "2104",
		"name_en": "Payroll Payables",
		"name_ar": "أجور ومرتبات مستحقة",
		"type": "Liability",
		"group": 0,
		"parent": "21",
		"main": "Liabilities",
		"sub": "Payroll",
		"cash_flow_section": "Operating Activities",
		"working_capital_bucket": "Other Working Capital",
	},
	{
		"code": "2105",
		"name_en": "Customer Advances (Deferred Revenue)",
		"name_ar": "دفعات مقدمة من عملاء (إيراد مؤجل)",
		"type": "Liability",
		"group": 0,
		"parent": "21",
		"main": "Liabilities",
		"sub": "Deferred Revenue",
		"cash_flow_section": "Operating Activities",
		"working_capital_bucket": "Other Working Capital",
	},
	{
		"code": "2106",
		"name_en": "Lease Liability – Current (IFRS 16)",
		"name_ar": "التزام عقود إيجار – متداول (IFRS 16)",
		"type": "Liability",
		"group": 0,
		"parent": "21",
		"main": "Liabilities",
		"sub": "Leases",
		"cash_flow_section": "Financing Activities",
		"working_capital_bucket": "Exclude",
	},
	{
		"code": "2107",
		"name_en": "Projects - Retention Payable to Subcontractors",
		"name_ar": "المشاريع - ضمانات مستحقة لمقاولين من الباطن",
		"type": "Liability",
		"group": 0,
		"parent": "21",
		"main": "Liabilities",
		"sub": "Trade Payables",
		"cash_flow_section": "Operating Activities",
		"working_capital_bucket": "Trade Payables",
	},
	{
		"code": "2108",
		"name_en": "Projects - Deferred Revenue / Billings in Advance",
		"name_ar": "المشاريع - إيراد مؤجل / فواتير مقدمة",
		"type": "Liability",
		"group": 0,
		"parent": "21",
		"main": "Liabilities",
		"sub": "Deferred Revenue",
		"cash_flow_section": "Operating Activities",
		"working_capital_bucket": "Other Working Capital",
	},
	{
		"code": "2109",
		"name_en": "Projects - Accrued Subcontractor Claims",
		"name_ar": "المشاريع - مطالبات مقاولي الباطن المستحقة",
		"type": "Liability",
		"group": 0,
		"parent": "21",
		"main": "Liabilities",
		"sub": "Accruals",
		"cash_flow_section": "Operating Activities",
		"working_capital_bucket": "Trade Payables",
	},
	{
		"code": "22",
		"name_en": "Non-Current Liabilities",
		"name_ar": "الخصوم غير المتداولة",
		"type": "Liability",
		"group": 1,
		"parent": "2",
		"main": "Liabilities",
		"sub": "Non-Current Liabilities",
	},
	{
		"code": "2201",
		"name_en": "Bank Loans – Long Term",
		"name_ar": "قروض بنكية طويلة الأجل",
		"type": "Liability",
		"group": 0,
		"parent": "22",
		"main": "Liabilities",
		"sub": "Borrowings",
		"cash_flow_section": "Financing Activities",
		"working_capital_bucket": "Exclude",
	},
	{
		"code": "2202",
		"name_en": "Lease Liability – Non-Current (IFRS 16)",
		"name_ar": "التزام عقود إيجار – غير متداول (IFRS 16)",
		"type": "Liability",
		"group": 0,
		"parent": "22",
		"main": "Liabilities",
		"sub": "Leases",
		"cash_flow_section": "Financing Activities",
		"working_capital_bucket": "Exclude",
	},
	# Equity
	{
		"code": "3",
		"name_en": "Equity",
		"name_ar": "حقوق الملكية",
		"type": "Equity",
		"group": 1,
		"main": "Equity",
		"sub": "Header",
	},
	{
		"code": "3101",
		"name_en": "Share Capital",
		"name_ar": "رأس المال المدفوع",
		"type": "Equity",
		"group": 0,
		"parent": "3",
		"main": "Equity",
		"sub": "Capital",
		"cash_flow_section": "Financing Activities",
		"working_capital_bucket": "Exclude",
	},
	{
		"code": "3102",
		"name_en": "Retained Earnings",
		"name_ar": "الأرباح المحتجزة",
		"type": "Equity",
		"group": 0,
		"parent": "3",
		"main": "Equity",
		"sub": "Retained Earnings",
		"cash_flow_section": "Financing Activities",
		"working_capital_bucket": "Exclude",
	},
	{
		"code": "3103",
		"name_en": "Current Year Result (Closing)",
		"name_ar": "نتيجة العام الحالي (إقفال)",
		"type": "Equity",
		"group": 0,
		"parent": "3",
		"main": "Equity",
		"sub": "P&L Reserve",
		"cash_flow_section": "Exclude",
		"working_capital_bucket": "Exclude",
	},
	# Income
	{
		"code": "4",
		"name_en": "Income",
		"name_ar": "الإيرادات",
		"type": "Income",
		"group": 1,
		"main": "Income",
		"sub": "Header",
	},
	{
		"code": "4101",
		"name_en": "Sales Revenue",
		"name_ar": "إيرادات المبيعات",
		"type": "Income",
		"group": 0,
		"parent": "4",
		"main": "Income",
		"sub": "Revenue",
		"pl_bucket": "Revenue",
	},
	{
		"code": "4102",
		"name_en": "Service Revenue",
		"name_ar": "إيرادات الخدمات",
		"type": "Income",
		"group": 0,
		"parent": "4",
		"main": "Income",
		"sub": "Revenue",
		"pl_bucket": "Revenue",
	},
	{
		"code": "4109",
		"name_en": "Other Operating Income",
		"name_ar": "إيرادات تشغيلية أخرى",
		"type": "Income",
		"group": 0,
		"parent": "4",
		"main": "Income",
		"sub": "Other Income",
		"pl_bucket": "Other Income",
	},
	{
		"code": "4114",
		"name_en": "Projects - Contract Revenue (Progress Billing)",
		"name_ar": "المشاريع - إيرادات عقود (حسب الإنجاز)",
		"type": "Income",
		"group": 0,
		"parent": "4",
		"main": "Income",
		"sub": "Revenue",
		"pl_bucket": "Revenue",
	},
	{
		"code": "4115",
		"name_en": "Projects - Variation Orders Revenue",
		"name_ar": "المشاريع - إيراد أوامر التغيير",
		"type": "Income",
		"group": 0,
		"parent": "4",
		"main": "Income",
		"sub": "Revenue",
		"pl_bucket": "Revenue",
	},
	{
		"code": "4116",
		"name_en": "Projects - Claims & Incentives Revenue",
		"name_ar": "المشاريع - إيراد مطالبات وحوافز",
		"type": "Income",
		"group": 0,
		"parent": "4",
		"main": "Income",
		"sub": "Other Income",
		"pl_bucket": "Other Income",
	},
	# Expenses
	{
		"code": "5",
		"name_en": "Expenses",
		"name_ar": "المصروفات",
		"type": "Expense",
		"group": 1,
		"main": "Expense",
		"sub": "Header",
	},
	{
		"code": "5101",
		"name_en": "Cost of Goods Sold",
		"name_ar": "تكلفة المبيعات",
		"type": "Expense",
		"group": 0,
		"parent": "5",
		"main": "Expense",
		"sub": "COGS",
		"pl_bucket": "COGS",
	},
	{
		"code": "5102",
		"name_en": "Operating Expenses – General & Admin",
		"name_ar": "مصاريف تشغيلية – عموم وإدارة",
		"type": "Expense",
		"group": 0,
		"parent": "5",
		"main": "Expense",
		"sub": "OPEX",
		"pl_bucket": "Operating Expense",
	},
	{
		"code": "5103",
		"name_en": "Payroll & Employee Benefits",
		"name_ar": "أجور ومرتبات ومزايا الموظفين",
		"type": "Expense",
		"group": 0,
		"parent": "5",
		"main": "Expense",
		"sub": "Payroll",
		"pl_bucket": "Operating Expense",
	},
	{
		"code": "5104",
		"name_en": "Rent & Lease",
		"name_ar": "إيجارات وتأجير",
		"type": "Expense",
		"group": 0,
		"parent": "5",
		"main": "Expense",
		"sub": "OPEX",
		"pl_bucket": "Operating Expense",
	},
	{
		"code": "5105",
		"name_en": "Utilities & Communications",
		"name_ar": "مرافق واتصالات",
		"type": "Expense",
		"group": 0,
		"parent": "5",
		"main": "Expense",
		"sub": "OPEX",
		"pl_bucket": "Operating Expense",
	},
	{
		"code": "5106",
		"name_en": "Marketing & Business Development",
		"name_ar": "تسويق وتطوير أعمال",
		"type": "Expense",
		"group": 0,
		"parent": "5",
		"main": "Expense",
		"sub": "OPEX",
		"pl_bucket": "Operating Expense",
	},
	{
		"code": "5107",
		"name_en": "Professional & Legal Fees",
		"name_ar": "اتعاب مهنية وقانونية",
		"type": "Expense",
		"group": 0,
		"parent": "5",
		"main": "Expense",
		"sub": "OPEX",
		"pl_bucket": "Operating Expense",
	},
	{
		"code": "5108",
		"name_en": "Depreciation & Amortization",
		"name_ar": "إهلاك واستهلاك",
		"type": "Expense",
		"group": 0,
		"parent": "5",
		"main": "Expense",
		"sub": "D&A",
		"pl_bucket": "Operating Expense",
	},
	{
		"code": "5110",
		"name_en": "Depreciation – Right-of-Use Assets (IFRS 16)",
		"name_ar": "إهلاك أصول حق الاستخدام (IFRS 16)",
		"type": "Expense",
		"group": 0,
		"parent": "5",
		"main": "Expense",
		"sub": "D&A",
		"pl_bucket": "Operating Expense",
	},
	{
		"code": "5113",
		"name_en": "Projects - Direct Materials",
		"name_ar": "المشاريع - مواد مباشرة",
		"type": "Expense",
		"group": 0,
		"parent": "5",
		"main": "Expense",
		"sub": "Direct Materials",
		"pl_bucket": "COGS",
	},
	{
		"code": "5114",
		"name_en": "Projects - Direct Labor",
		"name_ar": "المشاريع - عمالة مباشرة",
		"type": "Expense",
		"group": 0,
		"parent": "5",
		"main": "Expense",
		"sub": "Direct Labor",
		"pl_bucket": "COGS",
	},
	{
		"code": "5115",
		"name_en": "Projects - Subcontractor Costs",
		"name_ar": "المشاريع - تكاليف مقاولين من الباطن",
		"type": "Expense",
		"group": 0,
		"parent": "5",
		"main": "Expense",
		"sub": "COGS",
		"pl_bucket": "COGS",
	},
	{
		"code": "5116",
		"name_en": "Projects - Site Overheads",
		"name_ar": "المشاريع - مصروفات موقع",
		"type": "Expense",
		"group": 0,
		"parent": "5",
		"main": "Expense",
		"sub": "Manufacturing Overhead",
		"pl_bucket": "Operating Expense",
	},
	{
		"code": "5117",
		"name_en": "Projects - Mobilization & Demobilization",
		"name_ar": "المشاريع - تعبئة وإنهاء موقع",
		"type": "Expense",
		"group": 0,
		"parent": "5",
		"main": "Expense",
		"sub": "General & Administrative",
		"pl_bucket": "Operating Expense",
	},
	{
		"code": "5109",
		"name_en": "Finance Costs (Interest & Bank Charges)",
		"name_ar": "تكاليف تمويل (فوائد وعمولات بنكية)",
		"type": "Expense",
		"group": 0,
		"parent": "5",
		"main": "Expense",
		"sub": "Finance",
		"pl_bucket": "Other Expense",
	},
]


def _ext(rows: list[dict]) -> list[dict]:
	return list(rows)


ACTIVITY_EXTENSIONS: dict[str, list[dict]] = {
	"General": _ext(
		[
			{
				"code": "4111",
				"name_en": "Miscellaneous Operating Revenue",
				"name_ar": "إيرادات تشغيلية متنوعة",
				"type": "Income",
				"group": 0,
				"parent": "4",
				"main": "Income",
				"sub": "Revenue",
				"pl_bucket": "Revenue",
			},
			{
				"code": "5111",
				"name_en": "Repairs & Maintenance",
				"name_ar": "صيانة وإصلاحات",
				"type": "Expense",
				"group": 0,
				"parent": "5",
				"main": "Expense",
				"sub": "OPEX",
				"pl_bucket": "Operating Expense",
			},
		]
	),
	"Construction": _ext(
		[
			{
				"code": "4110",
				"name_en": "Contract Revenue – Progress Billing",
				"name_ar": "إيرادات عقود إنشاءات (فوترة حسب الإنجاز)",
				"type": "Income",
				"group": 0,
				"parent": "4",
				"main": "Income",
				"sub": "Contract Revenue",
				"pl_bucket": "Revenue",
			},
			{
				"code": "4112",
				"name_en": "Retention Receivable – Customers",
				"name_ar": "ضمان أعمال مسترد من العملاء",
				"type": "Asset",
				"group": 0,
				"parent": "11",
				"main": "Assets",
				"sub": "Receivables",
				"working_capital_bucket": "Trade Receivables",
			},
			{
				"code": "4113",
				"name_en": "Contract Assets (Unbilled Revenue)",
				"name_ar": "أصول عقود (إيراد غير مفوتر)",
				"type": "Asset",
				"group": 0,
				"parent": "11",
				"main": "Assets",
				"sub": "Contract Assets",
				"working_capital_bucket": "Other Working Capital",
			},
			{
				"code": "2106",
				"name_en": "Retention Payable – Subcontractors",
				"name_ar": "ضمان أعمال مستحق للمقاولين من الباطن",
				"type": "Liability",
				"group": 0,
				"parent": "21",
				"main": "Liabilities",
				"sub": "Payables",
				"working_capital_bucket": "Trade Payables",
			},
			{
				"code": "5110",
				"name_en": "Construction Cost – Materials & Subcontractors",
				"name_ar": "تكلفة إنشاءات – مواد ومقاولون من الباطن",
				"type": "Expense",
				"group": 0,
				"parent": "5",
				"main": "Expense",
				"sub": "Direct Cost",
				"pl_bucket": "COGS",
			},
			{
				"code": "5112",
				"name_en": "Site Overheads & Equipment Hire",
				"name_ar": "مصاريف موقع وتأجير معدات",
				"type": "Expense",
				"group": 0,
				"parent": "5",
				"main": "Expense",
				"sub": "Site Overhead",
				"pl_bucket": "Operating Expense",
			},
		]
	),
	"Engineering Consulting": _ext(
		[
			{
				"code": "4121",
				"name_en": "Consulting Fees – Time & Materials",
				"name_ar": "اتعاب استشارية – وقت ومواد",
				"type": "Income",
				"group": 0,
				"parent": "4",
				"main": "Income",
				"sub": "Professional Revenue",
				"pl_bucket": "Revenue",
			},
			{
				"code": "4122",
				"name_en": "Consulting Fees – Fixed Fee Engagements",
				"name_ar": "اتعاب استشارية – اتفاقيات أتعاب ثابتة",
				"type": "Income",
				"group": 0,
				"parent": "4",
				"main": "Income",
				"sub": "Professional Revenue",
				"pl_bucket": "Revenue",
			},
			{
				"code": "5121",
				"name_en": "Subconsultant & Outsourced Technical Services",
				"name_ar": "خدمات فنية بالوكالة ومستشارون فرعيون",
				"type": "Expense",
				"group": 0,
				"parent": "5",
				"main": "Expense",
				"sub": "COS Services",
				"pl_bucket": "COGS",
			},
			{
				"code": "5122",
				"name_en": "Bid & Proposal Costs",
				"name_ar": "تكاليف عروض ومناقصات",
				"type": "Expense",
				"group": 0,
				"parent": "5",
				"main": "Expense",
				"sub": "OPEX",
				"pl_bucket": "Operating Expense",
			},
		]
	),
	"Healthcare": _ext(
		[
			{
				"code": "4120",
				"name_en": "Patient Services Revenue",
				"name_ar": "إيرادات خدمات المرضى",
				"type": "Income",
				"group": 0,
				"parent": "4",
				"main": "Income",
				"sub": "Clinical Revenue",
				"pl_bucket": "Revenue",
			},
			{
				"code": "4123",
				"name_en": "Pharmacy & Retail Sales",
				"name_ar": "مبيعات صيدلية وتجزئة",
				"type": "Income",
				"group": 0,
				"parent": "4",
				"main": "Income",
				"sub": "Pharmacy",
				"pl_bucket": "Revenue",
			},
			{
				"code": "4124",
				"name_en": "Laboratory & Diagnostics Revenue",
				"name_ar": "إيرادات مختبر وتشخيص",
				"type": "Income",
				"group": 0,
				"parent": "4",
				"main": "Income",
				"sub": "Lab",
				"pl_bucket": "Revenue",
			},
			{
				"code": "5120",
				"name_en": "Medical Supplies & Consumables",
				"name_ar": "مستلزمات ومستهلكات طبية",
				"type": "Expense",
				"group": 0,
				"parent": "5",
				"main": "Expense",
				"sub": "Medical Supplies",
				"pl_bucket": "COGS",
			},
			{
				"code": "5123",
				"name_en": "Sterilization & Laundry Services",
				"name_ar": "خدمات تعقيم ومغاسل",
				"type": "Expense",
				"group": 0,
				"parent": "5",
				"main": "Expense",
				"sub": "Clinical OPEX",
				"pl_bucket": "Operating Expense",
			},
		]
	),
	"Education": _ext(
		[
			{
				"code": "4130",
				"name_en": "Tuition & Course Fees",
				"name_ar": "رسوم دراسية ودورات",
				"type": "Income",
				"group": 0,
				"parent": "4",
				"main": "Income",
				"sub": "Tuition",
				"pl_bucket": "Revenue",
			},
			{
				"code": "4131",
				"name_en": "Registration & Admission Fees",
				"name_ar": "رسوم تسجيل وقبول",
				"type": "Income",
				"group": 0,
				"parent": "4",
				"main": "Income",
				"sub": "Fees",
				"pl_bucket": "Revenue",
			},
			{
				"code": "4132",
				"name_en": "Grants & Sponsorship Income",
				"name_ar": "منح وإيرادات رعاية",
				"type": "Income",
				"group": 0,
				"parent": "4",
				"main": "Income",
				"sub": "Grants",
				"pl_bucket": "Other Income",
			},
			{
				"code": "5130",
				"name_en": "Faculty & Academic Staff Payroll",
				"name_ar": "أجور هيئة تدريس وكادر أكاديمي",
				"type": "Expense",
				"group": 0,
				"parent": "5",
				"main": "Expense",
				"sub": "Academic OPEX",
				"pl_bucket": "Operating Expense",
			},
			{
				"code": "5131",
				"name_en": "Learning Materials & Library",
				"name_ar": "مواد تعليمية ومكتبة",
				"type": "Expense",
				"group": 0,
				"parent": "5",
				"main": "Expense",
				"sub": "Academic OPEX",
				"pl_bucket": "Operating Expense",
			},
		]
	),
	"Manufacturing": _ext(
		[
			{
				"code": "4140",
				"name_en": "Finished Goods Sales",
				"name_ar": "مبيعات منتجات تامة",
				"type": "Income",
				"group": 0,
				"parent": "4",
				"main": "Income",
				"sub": "Manufacturing Revenue",
				"pl_bucket": "Revenue",
			},
			{
				"code": "4141",
				"name_en": "Scrap & By-Product Sales",
				"name_ar": "مبيعات خردة ومنتجات ثانوية",
				"type": "Income",
				"group": 0,
				"parent": "4",
				"main": "Income",
				"sub": "Other Income",
				"pl_bucket": "Other Income",
			},
			{
				"code": "1108",
				"name_en": "Raw Materials Inventory",
				"name_ar": "مخزون مواد أولية",
				"type": "Asset",
				"group": 0,
				"parent": "11",
				"main": "Assets",
				"sub": "Inventory",
				"is_stock_valuation": 1,
				"working_capital_bucket": "Inventory",
			},
			{
				"code": "1109",
				"name_en": "Work in Progress (WIP)",
				"name_ar": "إنتاج تحت التشغيل",
				"type": "Asset",
				"group": 0,
				"parent": "11",
				"main": "Assets",
				"sub": "WIP",
				"working_capital_bucket": "Inventory",
			},
			{
				"code": "5140",
				"name_en": "Direct Labor – Production",
				"name_ar": "أجور مباشرة – إنتاج",
				"type": "Expense",
				"group": 0,
				"parent": "5",
				"main": "Expense",
				"sub": "Manufacturing",
				"pl_bucket": "COGS",
			},
			{
				"code": "5141",
				"name_en": "Manufacturing Overhead (Allocated)",
				"name_ar": "أعباء تصنيعية (موزعة)",
				"type": "Expense",
				"group": 0,
				"parent": "5",
				"main": "Expense",
				"sub": "Overhead",
				"pl_bucket": "COGS",
			},
		]
	),
	"Tourism": _ext(
		[
			{
				"code": "4150",
				"name_en": "Room Revenue – Hotels",
				"name_ar": "إيرادات غرف فنادق",
				"type": "Income",
				"group": 0,
				"parent": "4",
				"main": "Income",
				"sub": "Hospitality Revenue",
				"pl_bucket": "Revenue",
			},
			{
				"code": "4151",
				"name_en": "Food & Beverage Revenue",
				"name_ar": "إيرادات مطاعم ومشروبات",
				"type": "Income",
				"group": 0,
				"parent": "4",
				"main": "Income",
				"sub": "F&B",
				"pl_bucket": "Revenue",
			},
			{
				"code": "4152",
				"name_en": "Tour Packages & Excursions",
				"name_ar": "باقات سياحة ورحلات",
				"type": "Income",
				"group": 0,
				"parent": "4",
				"main": "Income",
				"sub": "Tours",
				"pl_bucket": "Revenue",
			},
			{
				"code": "5150",
				"name_en": "Housekeeping & Guest Supplies",
				"name_ar": "تدبير فندقي وتوريدات ضيوف",
				"type": "Expense",
				"group": 0,
				"parent": "5",
				"main": "Expense",
				"sub": "Hospitality OPEX",
				"pl_bucket": "Operating Expense",
			},
			{
				"code": "5151",
				"name_en": "F&B Cost of Sales",
				"name_ar": "تكلفة مبيعات مطاعم ومشروبات",
				"type": "Expense",
				"group": 0,
				"parent": "5",
				"main": "Expense",
				"sub": "COGS F&B",
				"pl_bucket": "COGS",
			},
		]
	),
	"Trading": _ext(
		[
			{
				"code": "4160",
				"name_en": "Wholesale & Distribution Revenue",
				"name_ar": "إيرادات جملة وتوزيع",
				"type": "Income",
				"group": 0,
				"parent": "4",
				"main": "Income",
				"sub": "Trading",
				"pl_bucket": "Revenue",
			},
			{
				"code": "4161",
				"name_en": "Import Duties & Clearing Recoveries",
				"name_ar": "استردادات جمارك وتخليص",
				"type": "Income",
				"group": 0,
				"parent": "4",
				"main": "Income",
				"sub": "Other Income",
				"pl_bucket": "Other Income",
			},
			{
				"code": "5160",
				"name_en": "Freight, Logistics & Customs Charges",
				"name_ar": "شحن ولوجستيات وجمارك",
				"type": "Expense",
				"group": 0,
				"parent": "5",
				"main": "Expense",
				"sub": "Distribution",
				"pl_bucket": "Operating Expense",
			},
			{
				"code": "5161",
				"name_en": "Inventory Shrinkage & Obsolescence",
				"name_ar": "هالك مخزون وتقادم",
				"type": "Expense",
				"group": 0,
				"parent": "5",
				"main": "Expense",
				"sub": "Inventory",
				"pl_bucket": "Operating Expense",
			},
		]
	),
	"Services": _ext(
		[
			{
				"code": "4170",
				"name_en": "Managed Services Revenue",
				"name_ar": "إيرادات خدمات مُدارة",
				"type": "Income",
				"group": 0,
				"parent": "4",
				"main": "Income",
				"sub": "Services",
				"pl_bucket": "Revenue",
			},
			{
				"code": "4171",
				"name_en": "Subscription & Retainer Revenue",
				"name_ar": "إيرادات اشتراكات واتعاب دورية",
				"type": "Income",
				"group": 0,
				"parent": "4",
				"main": "Income",
				"sub": "Recurring",
				"pl_bucket": "Revenue",
			},
			{
				"code": "5170",
				"name_en": "Delivery & Field Operations",
				"name_ar": "تسليم وعمليات ميدانية",
				"type": "Expense",
				"group": 0,
				"parent": "5",
				"main": "Expense",
				"sub": "COS Services",
				"pl_bucket": "COGS",
			},
			{
				"code": "5171",
				"name_en": "Cloud & Software Licenses (COGS)",
				"name_ar": "سحابة وتراخيص برمجيات (تكلفة خدمة)",
				"type": "Expense",
				"group": 0,
				"parent": "5",
				"main": "Expense",
				"sub": "COS Services",
				"pl_bucket": "COGS",
			},
		]
	),
	"Financial Services": _ext(
		[
			{
				"code": "4180",
				"name_en": "Interest Income – Loans & Advances",
				"name_ar": "إيرادات فوائد – قروض وسلف",
				"type": "Income",
				"group": 0,
				"parent": "4",
				"main": "Income",
				"sub": "NII",
				"pl_bucket": "Revenue",
			},
			{
				"code": "4181",
				"name_en": "Fee & Commission Income",
				"name_ar": "إيرادات عمولات واتعاب",
				"type": "Income",
				"group": 0,
				"parent": "4",
				"main": "Income",
				"sub": "Fees",
				"pl_bucket": "Revenue",
			},
			{
				"code": "4182",
				"name_en": "FX & Trading Gain (Operating)",
				"name_ar": "أرباح صرف وتداول (تشغيلية)",
				"type": "Income",
				"group": 0,
				"parent": "4",
				"main": "Income",
				"sub": "Trading",
				"pl_bucket": "Other Income",
			},
			{
				"code": "5180",
				"name_en": "Interest Expense – Customer Deposits & Funding",
				"name_ar": "مصروف فوائد – ودائع وتمويل",
				"type": "Expense",
				"group": 0,
				"parent": "5",
				"main": "Expense",
				"sub": "Finance",
				"pl_bucket": "Other Expense",
			},
			{
				"code": "5181",
				"name_en": "Loan Loss Provision / Expected Credit Loss",
				"name_ar": "مخصص خسائر ائتمان / خسارة ائتمان متوقعة",
				"type": "Expense",
				"group": 0,
				"parent": "5",
				"main": "Expense",
				"sub": "Risk",
				"pl_bucket": "Operating Expense",
			},
		]
	),
	"Statutory Audit": _ext(
		[
			{
				"code": "4190",
				"name_en": "Audit & Assurance Fees Revenue",
				"name_ar": "إيرادات أتعاب مراجعة وتأكيد",
				"type": "Income",
				"group": 0,
				"parent": "4",
				"main": "Income",
				"sub": "Audit Revenue",
				"pl_bucket": "Revenue",
			},
			{
				"code": "4191",
				"name_en": "Non-Audit Advisory Fees Revenue",
				"name_ar": "إيرادات استشارات غير مراجعة",
				"type": "Income",
				"group": 0,
				"parent": "4",
				"main": "Income",
				"sub": "Advisory",
				"pl_bucket": "Revenue",
			},
			{
				"code": "5190",
				"name_en": "Engagement Staff Costs (Chargeable)",
				"name_ar": "تكلفة كادر مهام (قابلة للتحميل)",
				"type": "Expense",
				"group": 0,
				"parent": "5",
				"main": "Expense",
				"sub": "COS Audit",
				"pl_bucket": "COGS",
			},
			{
				"code": "5191",
				"name_en": "Quality Review & Independence Compliance",
				"name_ar": "مراجعة جودة والتزام استقلال",
				"type": "Expense",
				"group": 0,
				"parent": "5",
				"main": "Expense",
				"sub": "Compliance",
				"pl_bucket": "Operating Expense",
			},
		]
	),
	"Agriculture": _ext(
		[
			{
				"code": "4195",
				"name_en": "Crop & Produce Sales",
				"name_ar": "مبيعات محاصيل ومنتجات زراعية",
				"type": "Income",
				"group": 0,
				"parent": "4",
				"main": "Income",
				"sub": "Agri Revenue",
				"pl_bucket": "Revenue",
			},
			{
				"code": "4196",
				"name_en": "Livestock & Dairy Revenue",
				"name_ar": "إيرادات مواشي وألبان",
				"type": "Income",
				"group": 0,
				"parent": "4",
				"main": "Income",
				"sub": "Agri Revenue",
				"pl_bucket": "Revenue",
			},
			{
				"code": "5195",
				"name_en": "Fertilizers, Seeds & Crop Inputs",
				"name_ar": "أسمدة وبذور ومدخلات زراعية",
				"type": "Expense",
				"group": 0,
				"parent": "5",
				"main": "Expense",
				"sub": "Agri COGS",
				"pl_bucket": "COGS",
			},
			{
				"code": "5196",
				"name_en": "Irrigation, Fuel & Field Operations",
				"name_ar": "ري ووقود وعمليات حقلية",
				"type": "Expense",
				"group": 0,
				"parent": "5",
				"main": "Expense",
				"sub": "Agri OPEX",
				"pl_bucket": "Operating Expense",
			},
		]
	),
}

# Hotel / fixed-asset operations vertical: reuse hospitality CoA slice until a dedicated template exists.
ACTIVITY_EXTENSIONS["Hotel Assets (إدارة أصول الفنادق)"] = ACTIVITY_EXTENSIONS["Tourism"]
